export const refs = {
    input: document.querySelector(".search__query"),
    formButton: document.querySelector(".form__button"),
    search: document.querySelector(".search-form"),
    gallery: document.querySelector(".gallery"),
    loadMore: document.querySelector(".load-more"),
    futter: document.querySelector(".futter"),
    pageCounter: document.querySelector(".count__pages"),
    imageCounter: document.querySelector(".count__images"),
    pageCurrent: document.querySelector(".count__current"),
    pageTotal: document.querySelector(".count__total"),
    page: document.querySelector(".page__text"),
    pages: document.querySelector(".pages__text"),
    imageAvailable: document.querySelector(".images__available"),
    imageTotal: document.querySelector(".images__total"),
    progressContainer: document.querySelector(".progress-container"),
    scrollIndicator: document.getElementById("myBar"),
    menuButton: document.querySelector(".menu_btn"),
    menu: document.querySelector(".menu__content"),
    menuIcon: document.querySelector(".menu_icon"),
    loadType: document.getElementById("loadType"),
    loadInfo: document.getElementById("loadInfo"),
    authorInfo: document.getElementById("authorInfo"),
    overlay: document.querySelectorAll(".overlay"),
  };